import{initializeApp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import{getFirestore,collection,doc,setDoc,updateDoc,onSnapshot,query,orderBy,limit,runTransaction,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import{getAuth,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import{firebaseConfig,EVENT_ID}from"./firebase-config.js";import{questions}from"./questions.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app),$=id=>document.getElementById(id);
let uid=null,nickname="",idx=0,score=0,correct=0,unsub=null;
const norm=s=>s.trim().toLowerCase().replace(/\s+/g,"").replace(/[·ㆍ]/g,"");
const show=id=>{document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active")};
const pts=n=>n===1?100:n===2?90:n===3?80:70;
function ranks(){if(unsub)unsub();const q=query(collection(db,"events",EVENT_ID,"participants"),orderBy("score","desc"),limit(100));unsub=onSnapshot(q,s=>{const r=s.docs.map(d=>d.data());render(r)})}
function render(r){$("rankingList").innerHTML=r.slice(0,5).map((x,i)=>`<li class="${x.uid===uid?"me":""}"><b>${i+1}</b><span>${x.nickname}</span><strong>${x.score||0}</strong></li>`).join("");$("finalRanking").innerHTML=r.slice(0,20).map((x,i)=>`<li class="${x.uid===uid?"me":""}"><b>${i+1}</b><span>${x.nickname}</span><strong>${x.score||0}</strong></li>`).join("");const m=r.findIndex(x=>x.uid===uid);$("myRank").textContent=m>=0?`내 순위 ${m+1}위`:"내 순위 -";if(m>=0&&$("result").classList.contains("active"))$("resultRank").textContent=`${m+1}위`}
function draw(){const q=questions[idx];$("progress").textContent=`${idx+1} / ${questions.length}`;$("qno").textContent=`QUESTION ${String(idx+1).padStart(2,"0")}`;$("question").textContent=q.text;$("answer").value="";$("answer").disabled=false;$("submit").disabled=false;$("submit").textContent="정답 제출";$("feedback").textContent="";$("score").textContent=score;setTimeout(()=>$("answer").focus(),50)}
async function submit(){const input=$("answer"),btn=$("submit"),fb=$("feedback"),q=questions[idx],v=norm(input.value);if(!v){fb.textContent="정답을 입력해주세요.";fb.className="feedback wrong";return}input.disabled=true;btn.disabled=true;btn.textContent="확인 중...";const p=doc(db,"events",EVENT_ID,"participants",uid),qr=doc(db,"events",EVENT_ID,"questions",q.id),sr=doc(db,"events",EVENT_ID,"submissions",`${uid}_${q.id}`);try{const z=await runTransaction(db,async tx=>{const ps=await tx.get(p),qs=await tx.get(qr),ss=await tx.get(sr);if(ss.exists())return{duplicate:true,correct:false,points:0};const pd=ps.data()||{score:0,correctCount:0};if(norm(q.answer)!==v){tx.set(sr,{uid,nickname,questionId:q.id,correct:false,submittedAt:serverTimestamp()});return{duplicate:false,correct:false,points:0}}const order=Number(qs.exists()?qs.data().correctCount||0:0)+1,points=pts(order);tx.set(qr,{correctCount:order,updatedAt:serverTimestamp()},{merge:true});tx.set(sr,{uid,nickname,questionId:q.id,correct:true,order,points,submittedAt:serverTimestamp()});tx.update(p,{score:Number(pd.score||0)+points,correctCount:Number(pd.correctCount||0)+1,updatedAt:serverTimestamp()});return{duplicate:false,correct:true,points,order}});if(z.duplicate){fb.textContent="이미 제출한 문제입니다.";fb.className="feedback wrong"}else if(z.correct){score+=z.points;correct++;fb.textContent=`정답! ${z.order}번째 정답 · +${z.points}점 🎉`;fb.className="feedback correct"}else{fb.textContent="아쉽지만 오답이에요.";fb.className="feedback wrong"}$("score").textContent=score;setTimeout(()=>{if(idx<questions.length-1){idx++;draw()}else finish()},900)}catch(e){console.error(e);fb.textContent="제출 오류가 발생했습니다.";fb.className="feedback wrong";input.disabled=false;btn.disabled=false;btn.textContent="정답 제출"}}
async function finish(){await updateDoc(doc(db,"events",EVENT_ID,"participants",uid),{finished:true,finishedAt:serverTimestamp(),updatedAt:serverTimestamp()});$("resultName").textContent=nickname;$("resultScore").textContent=score;$("resultCorrect").textContent=correct;show("result")}
$("enterBtn").onclick=async()=>{const n=$("nickname").value.trim();if(n.length<2){alert("닉네임을 2글자 이상 입력해주세요.");return}if(!uid){alert("서버 연결 중입니다. 잠시만 기다려주세요.");return}nickname=n.slice(0,12);try{await setDoc(doc(db,"events",EVENT_ID,"participants",uid),{uid,nickname,score:0,correctCount:0,finished:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});idx=0;score=0;correct=0;ranks();show("quiz");draw()}catch(e){console.error(e);alert("입장에 실패했습니다. Firebase 설정/보안규칙을 확인해주세요.")}};
$("submit").onclick=submit;$("answer").onkeydown=e=>{if(e.key==="Enter")submit()};$("nickname").onkeydown=e=>{if(e.key==="Enter")$("enterBtn").click()};
onAuthStateChanged(auth,u=>{if(u){uid=u.uid;$("enterBtn").disabled=false}});$("enterBtn").disabled=true;signInAnonymously(auth).catch(e=>{console.error(e);alert("Firebase Authentication에서 익명 로그인을 활성화해주세요.")});
